title: Loyalty20 Rewards Programs
logo: /assets/img/logo.jpg
description: Loyalty Rewards Programs using Cryptocurrency. The Future of Shopping 
Loyalty20 Token makes your loyalty rewards tradeable 
start now to collect everywhere, exhange anytime and redeem whenever and wherever you like   
show_downloads: true  
google_analytics: wooriapt79
theme: jekyll-theme-minimal

# Site Author
author:
  name: Blockchain Lab
  avatar: Lab
  bio: Your biography for the left-hand sidebar
  location: Korea
