title: Loyalty Rewards Programs
logo: <img src="http://www.123card.kr/images/logo.png">
description: Loyalty Rewards Programs using Cryptocurrency 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

